// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPU_JvJk8zqpzPGxHmJ_UZQKSd1PSociY',
    appId: '1:9527223797:web:ddce35354f7879ad996cbc',
    messagingSenderId: '9527223797',
    projectId: 'brothers-creative',
    authDomain: 'brothers-creative.firebaseapp.com',
    storageBucket: 'brothers-creative.appspot.com',
    measurementId: 'G-0NG7QQ8F9K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9UQWdfrV9oWjMYsGjqD8ToxRK-Jx0IxQ',
    appId: '1:9527223797:android:7ff0fec7a325c921996cbc',
    messagingSenderId: '9527223797',
    projectId: 'brothers-creative',
    storageBucket: 'brothers-creative.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5qEp4r-MF_VAOOu4QFMG1Ec78Yy7J0vE',
    appId: '1:9527223797:ios:2c0533656262d1cb996cbc',
    messagingSenderId: '9527223797',
    projectId: 'brothers-creative',
    storageBucket: 'brothers-creative.appspot.com',
    androidClientId: '9527223797-lkibagbut7e2hj5ib3oghb25eglru94h.apps.googleusercontent.com',
    iosClientId: '9527223797-6hi10u3rsv38baklf1l49ni2lcc69jl0.apps.googleusercontent.com',
    iosBundleId: 'com.example.brotherStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5qEp4r-MF_VAOOu4QFMG1Ec78Yy7J0vE',
    appId: '1:9527223797:ios:2c0533656262d1cb996cbc',
    messagingSenderId: '9527223797',
    projectId: 'brothers-creative',
    storageBucket: 'brothers-creative.appspot.com',
    androidClientId: '9527223797-lkibagbut7e2hj5ib3oghb25eglru94h.apps.googleusercontent.com',
    iosClientId: '9527223797-6hi10u3rsv38baklf1l49ni2lcc69jl0.apps.googleusercontent.com',
    iosBundleId: 'com.example.brotherStore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAPU_JvJk8zqpzPGxHmJ_UZQKSd1PSociY',
    appId: '1:9527223797:web:36d2abfbecd7e091996cbc',
    messagingSenderId: '9527223797',
    projectId: 'brothers-creative',
    authDomain: 'brothers-creative.firebaseapp.com',
    storageBucket: 'brothers-creative.appspot.com',
    measurementId: 'G-N8Z3TZZK5D',
  );

}